#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc_bspwm &
dunst &
nm-applet &
nitrogen --restore
picom --experimental-backends &
unclutter &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#ffffff

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Qalculate-gtk state=floating
bspc rule -a fontforge state=floating
bspc rule -a Nitrogen state=floating

xsetroot -cursor_name left_ptr
